#!/bin/sh
set -e

#### Benchmark Library ####

# if [ ! -d "benchmark-1.7.1" ]
# then
#     echo "Downloading Google Benchmark Library"
#     curl -# -L "https://github.com/google/benchmark/archive/refs/tags/v1.7.1.tar.gz" | tar -xz
# fi

# if [ ! -f "./benchmark-1.7.1/build/src/libbenchmark.a" ] || [ ! -f "./benchmark-1.7.1/build/src/libbenchmark_main.a" ]
# then
#     cd benchmark-1.7.1/
#     cmake -E make_directory "build"
#     cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_LTO=true -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../
#     cmake --build "build" --config Release
#     cd ..
# fi

#### Target Programs ####

gcc run.c -o run
gcc run2.c -o run2
gcc run3.c -o run3
gcc run5.c -o run5
